export const EMPLOYMENT_TYPE = {
	FULL_TIME: "FULL_TIME",
	PART_TIME: "PART_TIME",
	CONTRACT: "CONTRACT",
	FREELANCE: "FREELANCE",
	INTERNSHIP: "INTERNSHIP",
} as const;

export type EmploymentType = (typeof EMPLOYMENT_TYPE)[keyof typeof EMPLOYMENT_TYPE];
