export const EVENT_NAMES = {
	//! IAM - Authentication & Sessions
	FAILED_LOGIN_ATTEMPTED: "FAILED_LOGIN_ATTEMPTED",
	USER_LOGGED_IN: "USER_LOGGED_IN",
	USER_SESSION_REVOKED: "USER_SESSION_REVOKED",
	USER_REGISTERED: "USER_REGISTERED",
	USER_EMAIL_VERIFIED: "USER_EMAIL_VERIFIED",
	VERIFICATION_EMAIL_RESENT: "VERIFICATION_EMAIL_RESENT",
	PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",

	//! IAM - Account & Profile
	USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
	AVATAR_UPLOADED: "AVATAR_UPLOADED",
	AVATAR_REMOVED: "AVATAR_REMOVED",
	EMAIL_CHANGE_REQUESTED: "EMAIL_CHANGE_REQUESTED",
	USER_EMAIL_CHANGED: "USER_EMAIL_CHANGED",
	INITIAL_PASSWORD_SET: "INITIAL_PASSWORD_SET",
	USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
	USER_ACCOUNT_DELETION_SCHEDULED: "USER_ACCOUNT_DELETION_SCHEDULED",
	USER_ACCOUNT_RESTORED: "USER_ACCOUNT_RESTORED",
	USER_ACCOUNT_DELETING: "USER_ACCOUNT_DELETING",
	USER_ACCOUNT_DELETED: "USER_ACCOUNT_DELETED",

	//! IAM - MFA & OAuth
	USER_MFA_ENABLED: "USER_MFA_ENABLED",
	USER_MFA_DISABLED: "USER_MFA_DISABLED",
	OAUTH_PROVIDER_LINKED: "OAUTH_PROVIDER_LINKED",
	OAUTH_PROVIDER_UNLINKED: "OAUTH_PROVIDER_UNLINKED",

	//! Recruitment - Applicants
	APPLICANT_PROFILE_CREATED: "APPLICANT_PROFILE_CREATED",
	APPLICANT_PROFILE_UPDATED: "APPLICANT_PROFILE_UPDATED",
	APPLICANT_DOCUMENT_UPLOADED: "APPLICANT_DOCUMENT_UPLOADED",
	APPLICANT_DOCUMENT_DELETED: "APPLICANT_DOCUMENT_DELETED",
	PRIMARY_DOCUMENT_SET: "PRIMARY_DOCUMENT_SET",
	SAVED_JOB_TOGGLED: "SAVED_JOB_TOGGLED",

	//! Recruitment - Employers
	EMPLOYER_PROFILE_CREATED: "EMPLOYER_PROFILE_CREATED",
	EMPLOYER_PROFILE_UPDATED: "EMPLOYER_PROFILE_UPDATED",
	COMPANY_LOGO_UPLOADED: "COMPANY_LOGO_UPLOADED",
	COMPANY_LOGO_REMOVED: "COMPANY_LOGO_REMOVED",

	//! Recruitment - Jobs
	JOB_LISTING_CREATED: "JOB_LISTING_CREATED",
	JOB_LISTING_UPDATED: "JOB_LISTING_UPDATED",
	JOB_LISTING_CLOSED: "JOB_LISTING_CLOSED",
	JOB_LISTING_EXPIRED: "JOB_LISTING_EXPIRED",

	//! Recruitment - Applications
	JOB_APPLICATION_SUBMITTED: "JOB_APPLICATION_SUBMITTED",
	JOB_APPLICATION_WITHDRAWN: "JOB_APPLICATION_WITHDRAWN",
	JOB_APPLICATION_STATUS_UPDATED: "JOB_APPLICATION_STATUS_UPDATED",
	INTERNAL_NOTE_UPDATED: "INTERNAL_NOTE_UPDATED",
} as const;

export type EventName = (typeof EVENT_NAMES)[keyof typeof EVENT_NAMES];
