import { env } from "@/env";
import { OAuthProfileDto, OAuthProviderPort } from "@/iam/application/ports/outbound";
import { OAuthProviderType } from "@/iam/domain/types";
import { Injectable } from "@nestjs/common";

interface ProviderConfig {
	clientId: string;
	clientSecret: string;
	redirectUri: string;
	authUrl: string;
	tokenUrl: string;
	profileUrl: string;
	authParams: Record<string, string>;
}

interface TokenResponse {
	access_token?: string;
	error?: string;
	error_description?: string;
}

interface GoogleProfileResponse {
	sub: string;
	email?: string;
	name: string;
	picture?: string;
	email_verified?: boolean;
}

interface GithubProfileResponse {
	id: number;
	name?: string;
	login: string;
	avatar_url?: string;
	email?: string;
}

interface GithubEmailResponse {
	email: string;
	primary: boolean;
	verified: boolean;
}

interface MicrosoftProfileResponse {
	id: string;
	displayName: string;
	mail?: string;
	userPrincipalName?: string;
}

@Injectable()
export class ManualOAuthAdapter implements OAuthProviderPort {
	/**
	 * Centralized configuration mapping for OAuth providers.
	 * Map the Domain's OAuthProviderType directly to the infrastructure environment variables and external provider URLs.
	 */
	private readonly config: Record<OAuthProviderType, ProviderConfig> = {
		GOOGLE: {
			clientId: env.GOOGLE_CLIENT_ID,
			clientSecret: env.GOOGLE_CLIENT_SECRET,
			redirectUri: env.GOOGLE_REDIRECT_URI,
			authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
			tokenUrl: "https://oauth2.googleapis.com/token",
			profileUrl: "https://openidconnect.googleapis.com/v1/userinfo",
			authParams: {
				response_type: "code",
				scope: "openid email profile",
				access_type: "offline",
				prompt: "consent",
			},
		},
		GITHUB: {
			clientId: "", // Placeholder until added to env.ts
			clientSecret: "",
			redirectUri: "",
			authUrl: "https://github.com/login/oauth/authorize",
			tokenUrl: "https://github.com/login/oauth/access_token",
			profileUrl: "https://api.github.com/user",
			authParams: {
				scope: "read:user user:email",
			},
		},
		MICROSOFT: {
			clientId: "", // Placeholder until added to env.ts
			clientSecret: "",
			redirectUri: "",
			authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
			tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
			profileUrl: "https://graph.microsoft.com/v1.0/me",
			authParams: {
				response_type: "code",
				scope: "openid email profile User.Read",
				response_mode: "query",
			},
		},
	};

	/**
	 * STEP 2: Generate Authorization URL (Phase 1 of OAuth 2.0 Flow)
	 * Constructs the URL that the frontend will redirect the user to.
	 * This includes the CSRF `state` parameter generated by our application layer.
	 */
	public getAuthorizationUrl(provider: OAuthProviderType, state: string): Promise<string> {
		const providerCfg = this.config[provider];

		if (!providerCfg.clientId) {
			return Promise.reject(
				new Error(`OAuth Provider '${provider}' is not fully configured yet. Missing Client ID.`),
			);
		}

		const params = new URLSearchParams({
			client_id: providerCfg.clientId,
			redirect_uri: providerCfg.redirectUri,
			state,
			...providerCfg.authParams,
		});

		return Promise.resolve(`${providerCfg.authUrl}?${params.toString()}`);
	}

	/**
	 * STEP 3: Exchange Orchestration (Phase 2 of OAuth 2.0 Flow)
	 * Once the user approves the login, the provider redirects back to our callback endpoint
	 * with an authorization `code`. We exchange this code for an access token, then fetch the profile.
	 */
	public async exchangeCodeForProfile(
		provider: OAuthProviderType,
		code: string,
	): Promise<OAuthProfileDto> {
		const providerCfg = this.config[provider];

		if (!providerCfg.clientId || !providerCfg.clientSecret) {
			throw new Error(`OAuth Provider '${provider}' is missing credentials for token exchange.`);
		}

		const accessToken = await this.fetchAccessToken(provider, providerCfg, code);
		return await this.fetchUserProfile(provider, providerCfg, accessToken);
	}

	/**
	 * STEP 4: Token Exchange HTTP Request
	 * Executes a secure server-to-server POST request to the provider's token endpoint.
	 * Passes the client secret so the provider knows this request is genuinely from our backend.
	 */
	private async fetchAccessToken(
		provider: OAuthProviderType,
		providerCfg: ProviderConfig,
		code: string,
	): Promise<string> {
		const bodyParams = new URLSearchParams({
			client_id: providerCfg.clientId,
			client_secret: providerCfg.clientSecret,
			code,
			redirect_uri: providerCfg.redirectUri,
			grant_type: "authorization_code",
		});

		const response = await fetch(providerCfg.tokenUrl, {
			method: "POST",
			headers: {
				"Content-Type": "application/x-www-form-urlencoded",
				Accept: "application/json",
			},
			body: bodyParams.toString(),
		});

		const data = (await response.json()) as TokenResponse;

		if (!response.ok || !data.access_token) {
			throw new Error(
				data.error_description ?? data.error ?? `Failed to retrieve access token from ${provider}`,
			);
		}

		return data.access_token;
	}

	/**
	 * STEP 5: Profile Data Extraction and Normalization
	 * Uses the newly acquired access token to fetch the user's identity details.
	 * Maps the disparate provider JSON responses into our unified `OAuthProfileDto` standard.
	 */
	private async fetchUserProfile(
		provider: OAuthProviderType,
		providerCfg: ProviderConfig,
		accessToken: string,
	): Promise<OAuthProfileDto> {
		const headers = {
			Authorization: `Bearer ${accessToken}`,
			Accept: "application/json",
		};

		switch (provider) {
			case "GOOGLE": {
				const res = await fetch(providerCfg.profileUrl, { headers });
				const data = (await res.json()) as GoogleProfileResponse;

				return {
					provider: "GOOGLE",
					providerAccountId: data.sub,
					email: data.email ?? null,
					name: data.name,
					image: data.picture ?? null,
					isEmailVerified: data.email_verified ?? true,
				};
			}

			case "GITHUB": {
				const userRes = await fetch(providerCfg.profileUrl, { headers });
				const userData = (await userRes.json()) as GithubProfileResponse;

				let primaryEmail = userData.email ?? null;
				let isEmailVerified = false;

				//! GitHub requires a secondary fetch if the user's email is set to private
				if (!primaryEmail) {
					const emailsRes = await fetch("https://api.github.com/user/emails", { headers });
					if (emailsRes.ok) {
						const emailsData = (await emailsRes.json()) as GithubEmailResponse[];
						const primaryRecord = emailsData.find((e) => e.primary) ?? emailsData[0];

						if (primaryRecord) {
							primaryEmail = primaryRecord.email;
							isEmailVerified = primaryRecord.verified;
						}
					}
				} else {
					isEmailVerified = true;
				}

				return {
					provider: "GITHUB",
					providerAccountId: userData.id.toString(),
					email: primaryEmail,
					name: userData.name ?? userData.login,
					image: userData.avatar_url ?? null,
					isEmailVerified,
				};
			}

			case "MICROSOFT": {
				const res = await fetch(providerCfg.profileUrl, { headers });
				const data = (await res.json()) as MicrosoftProfileResponse;

				return {
					provider: "MICROSOFT",
					providerAccountId: data.id,
					email: data.mail ?? data.userPrincipalName ?? null,
					name: data.displayName,
					image: null,
					isEmailVerified: true,
				};
			}

			default:
				throw new Error(`Profile fetching mapping for ${String(provider)} is not implemented.`);
		}
	}
}
